server:
  port: 7070
spring:
  application:
    name: @project.artifactId@
  boot:
      admin:
        url: http://127.0.0.1:8088
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9090/eureka/

