server:
  port: 9092
spring:
  application:
    name: server-02
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://127.0.0.1:9090/eureka