server:
  port: 8088
spring:
  application:
    name: monitor
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9090/eureka/
  instance:
    lease-renewal-interval-in-seconds: 5
endpoints:
  health:
    sensitive: false