server:
  port: 8080
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ailot/spring-cloud.git
          search-paths: config-repo
  application:
    name: @project.artifactId@